config/routes.rb
Valuables::Application.routes.draw do
  devise_for :users
  
  root to: "home#index"
  
  resources :dashboard
  resources :items
  resources :pages
  
  match '/pricing' => 'pages#pricing'
  match '/about' => 'pages#about'
  match '/howitworks' => 'pages#howitworks'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :brand, :description, :name, :stolen, :image, :serial_number
  
  has_many :ownerships
  has_many :users, :through => :ownerships
  
  validates :brand, :description, :name, :presence => true
  validates :name, :length => { :minimum => 2 }
  validates :name, :uniqueness => true
  
  
  
  
  has_attached_file :image, styles: {
     thumb: '300x300>',
     square: '500x500>',
     medium: '800x800>'
  },
  :storage => :s3,
  :s3_credentials => "#{Rails.root}/config/s3.yml",
  :path =>"/assets/:user_id/:filename"
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  attr_accessible :item_id, :user_id
  
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :items, :through => :ownerships
  has_many :ownerships
  # attr_accessible :title, :body
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @user = current_user
    render :template => 'devise/passwords/edit', :locals => {:resource => current_user,:resource_name => User }
  end
  
  def show
    @user = current_user
    render '../views/devise/registrations/edit'
  end
  
  def edit
    @user = current_user
    render '../views/devise/registrations/edit'
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to :controller => "dashboard", :action => "index", :notice => "Your account was updated."
    else
      render "edit"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
    @user = current_user
    @items = current_user.items.all
    @stolenitems = current_user.items.find(:all, :conditions => {:stolen => true})
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to :controller=>'dashboard', :action => 'index'
    end
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  def index
    if user_signed_in?
      @items = current_user.items.all
    else
      redirect_to :controller => "home", :action => "index"
    end
  end
  
  def show
    @user = current_user
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
    @ownership = Ownership.new
  end
  
  def create
    @item = Item.new(params[:item])
        
    if @item.save
      @ownership = Ownership.new(:user_id => current_user.id, :item_id => @item.id)
      @ownership.save
      redirect_to items_path, :notice => "Item added."
      
    else
      render "new"
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      redirect_to items_path, :notice => "Your item was updated."
    else
      render "edit"
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    
    @item.destroy
    redirect_to items_path, :notice => "Item deleted"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
    
  end
  
  def pricing
    
  end
  
  def howitworks
    
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/accounts/index.html.erb
<%= render 'layouts/nav'%>

<h1>My Account</h1>

<%= render :partial => 'accountform' %>

app/views/dashboard/index.html.erb
<%= render 'layouts/nav'%>


<h1>Dashboard</h1>
<h3>Owned Items: <%= current_user.items.count %></h3>
<br />
<br />
<br />
<h3>My Unrecovered Stolen Items: <%= @stolenitems.count %></h3>

<% @stolenitems.each do |s| %>
	<ul>
		<li><%= s.name %></li>
		<!-- ><li><%= s.description %></li> -->
	</ul>
<% end %>

app/views/home/index.html.erb
<%= render 'layouts/nav'%>

	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
	
	<div class="row">
		<div class="span8 offset2">
			<h1 style="text-align: center">Swypd makes it easier than ever to secure and manage your stuff.</h1>
		</div>
	</div>
	<br />
	<br />
	<div class="row">
		<div class="span4 offset2">
			<img src="holder.js/400x300/social">
		</div>
		<div class="span4">
			<img src="holder.js/400x300/social">
		</div>
		
	</div>
	<br />
	<br />
	<div class="row">
		<div class="span8 offset2">
			<ul>
				<li><h3>Keep an inventory or your belongings</h3></li>
				<li><h3>Swypd tracks the serial numbers of your valuables</h3></li>
				<li><h3>Stolen items have a better chance of return</h3></li>
			</ul>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="span2 offset5">
			<h1 style="text-align: center"><%= link_to "Sign up", new_user_registration_path %></h1>
		</div>
	</div>

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :brand, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :brand, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :serial_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :serial_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stolen, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :stolen, :class => 'check_box' %>
    </div>
  </div>

  <div class="control-group">
  	<%= f.label :image %><br />
	<div class="controls">
	  <%= f.file_field :image%>
	</div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render 'layouts/nav'%>

<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%= render 'layouts/nav'%>


<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:serial_number) %></th>
      <th><%= model_class.human_attribute_name(:stolen) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= item.description %></td>
        <td><%= item.brand %></td>
        <td><%= item.serial_number %></td>
        <td><%= item.stolen %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%= render 'layouts/nav'%>

<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%= render 'layouts/nav'%>

<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @item.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @item.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand) %>:</strong></dt>
  <dd><%= @item.brand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serial_number) %>:</strong></dt>
  <dd><%= @item.serial_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stolen) %>:</strong></dt>
  <dd><%= @item.stolen %></dd>
  <%= image_tag @item.image.url(:square) %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/items/unrecovered.html.erb
<h1>Unrecovered Items</h1>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
		<div class="brand"><%= link_to "Swypd", :controller => "home", :action => "index"%></div>
        <div class="nav-collapse">
          <ul class="nav">
			<% if user_signed_in? %>
            	<li><%= link_to "Items", :controller => "items"%></li>
            	<li><%= link_to "Disputes" %></li>
            	<li><%= link_to "My Account", edit_user_registration_path %></li>
			<% else %>
				<li><%= link_to "About", :controller => "pages", :action => "about" %></li>
				<li><%= link_to "How it Works", :controller => "pages", :action => "howitworks" %></li>
				<li><%= link_to "Pricing", :controller => "pages", :action => "pricing" %></li>
				<li><%= link_to "Blog" %>
			<% end %>
			<li>
				<div style="display: inline-block; margin-top: 10px; margin-left: 15px;">
				  <% if user_signed_in? %>
				    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
				  <% else %>
				  	<%= link_to "Sign In", new_user_session_path %>
				  <% end %>
				</div>
			</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Valuables</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>

<script src="holder.js"></script>
</html>

app/views/pages/about.html.erb
<%= render 'layouts/nav'%>
<div class="row">
	<div class="span4 offset4">
		<h1 class="text-center">What is Swypd?</h1>
	</div>
</div>
<br />
<div class="row">
	<div class="row">
		<div class="span4 offset2">
			<img src="holder.js/400x300/social">
		</div>
		<div class="span4">
			<img src="holder.js/400x300/social">
		</div>
	</div>
</div>
<br />
<div class="row">
	<div class="row">
		<div class="span4 offset2">
			<img src="holder.js/400x300/social">
		</div>
		<div class="span4">
			<img src="holder.js/400x300/social">
		</div>
	</div>
</div>
<br />
<div class="row">
	<div class="span2 offset5">
		<h2 class="text-center"><%= link_to "Sign up", new_user_registration_path %></h2>
	</div>
</div>

app/views/pages/howitworks.html.erb
<%= render 'layouts/nav'%>
<h1>How does it work?</h1>

app/views/pages/pricing.html.erb
<%= render 'layouts/nav'%>
<h1>Pricing</h1>